spring:
  datasource:
    url: 'jdbc:mysql://122.9.47.93:3306/2046204601?
    createDatabaseIfNotExist=true
    &serverTimezone=Asia/Shanghai'
    username: 2046204601
    password: 2046204601
  sql:
    init:
      mode: always

logging:
  level:
    sql: debug
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'


