spring:
  datasource:
    url: 'jdbc:mysql://116.63.13.220/2046204601?createDatabaseIfNotExist=true'
    username: 2046204601
    password: 2046204601
  sql:
    init:
      mode: always

logging:
  level:
    sql: debug
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'


