POST http://localhost:8080/api/example06/login
Content-Type: application/json

{
  "userName": "BO",
  "password": "123456"
}

> {% client.global.set("token", response.headers.valueOf("token")); %}
### token为空。未登录请求
GET  http://localhost:8080/api/example06/admin/welcome

### 手动模拟合法token与role测试
GET  http://localhost:8080/api/example06/admin/welcome
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI5ODQxNjYyMTU4OCIsInJvbGUiOiJVOGdSNSIsImlhdCI6MTcxMzc3NzgwMCwiZXhwIjoxNzEzNzc3ODk0fQ.sEOw-6KO5FSfqmGk7iTOmaowvs2GZHM-PTfrimGOlSw
role: U8gR5

### 基于脚本自动获取token数据。便于测试
GET  http://localhost:8080/api/example06/admin/welcome
token: {{token}}