GET http://localhost:8080/api/users/1
###
GET http://localhost:8080/api/users/2
###

PATCH http://localhost:8080/api/users
Content-Type: application/json

{
  "id": "1",
  "name": "LIU"
}
###
DELETE http://localhost:8080/api/users/1
###
GET http://localhost:8080/api/users/