spring:
  # 使用独立redisson配置时，不在spring.data.redis路径下
  redis:
    redisson:
      file: classpath:redisson.yml

logging:
  level:
    root: warn
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
