spring:
  data:
    redis:
      host: 120.46.159.231
      port: 6379 # 使用默认端口时无需声明
      username: default
      password: 2046
      database: 0 # 替换数据库编号

logging:
  level:
    root: warn
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
