db-account: 2046204600 # 可声明变量多处引用，避免出错
spring:
  datasource:
    url: 'jdbc:postgresql://192.168.1.31:5432/${db-account}'
    username: ${db-account}
    password: ${db-account}

  sql:
    init:
      mode: always

logging:
  level:
    root: warn
    sql: debug
    org.example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
